export const IMAGENS = [
	"C:/Aurora-alejandro-schmechel.jpg",
	"C:/Aurora-ana-nornberg.jpg",
	"C:/Aurora-anderson-cardozo.jpg",
	"C:/Aurora-andreo-batista.jpg",
	"C:/Aurora-angelo-lages.jpg",
	"C:/Aurora-arthur-moreno.jpg",
	"C:/Aurora-bruno-almeida.jpg",
	"C:/Aurora-bruno-prestes.jpg",
	"C:/Aurora-camille-voigt.jpg",
	"C:/Aurora-carlo-schneider.jpg",
	"C:/Aurora-daniel-afonso.jpg",
	"C:/Aurora-daniel-arend.jpg",
	"C:/Aurora-diego-soliveira.jpg",
	"C:/Gaia-alana-campos.jpg",
	"C:/Gaia-alice-goncalves.jpg",
	"C:/Gaia-alice-rezende.jpg",
	"C:/Gaia-aline-mendes.jpg",
	"C:/Gaia-ana-marzano.jpg",
	"C:/Gaia-ana-souto.jpg",
	"C:/Gaia-andre-batista.jpg",
	"C:/Gaia-andressa-santos.jpg",
	"C:/Gaia-anielly-goncalves.jpg",
	"C:/Gaia-anna-souza.jpg",
	"C:/Gaia-bruna-alvim.jpg",
	"C:/Gaia-camila-bicalho.jpg",
	"C:/Gaia-clesio-silva.jpg",
	"C:/Gaia-dalmir-collina.jpg",
	"C:/Gaia-daniel-soares.jpg",
	"C:/Gaia-davi-teixeira.jpg",
	"C:/Hakuna-ademir-leal.jpg",
	"C:/Hakuna-adriana-alcantara.jpg",
	"C:/Hakuna-adriano-braga.jpg",
	"C:/Hakuna-alexandre-loriggio.jpg",
	"C:/Hakuna-alexsandro-oliveira.jpg",
	"C:/Hakuna-ana-aragao.jpg",
	"C:/Hakuna-ana-dias.jpg",
	"C:/Hakuna-ana-ferraz.jpg",
	"C:/Hakuna-ana-gouvea.jpg",
	"C:/Hakuna-ana-magni.jpg",
	"C:/Hakuna-ana-siqueira.jpg",
	"C:/Hakuna-arthur-alves.jpg",
	"C:/Hakuna-arthur-linhares.jpg",
	"C:/Hakuna-arthur-parreiras.jpg",
	"C:/Hakuna-breno-barbosa.jpg",
	"C:/Hakuna-breno-furtado.jpg",
	"C:/Hakuna-breno-mascarenhas.jpg",
	"C:/Hakuna-bruno-aguiar.jpg",
	"C:/Hakuna-bruno-pego.jpg",
	"C:/Hakuna-bryan-gomes.jpg",
	"C:/Hakuna-caio-magno.jpg",
	"C:/Hakuna-carla-grande.jpg",
	"C:/Hakuna-carlos-fonseca.jpg",
	"C:/Hakuna-clarissa-reis.jpg",
	"C:/Hakuna-dalila-araujo.jpg",
	"C:/Hakuna-daniel-vargas.jpg",
	"C:/Hakuna-danilo-franco.jpg",
	"C:/Hakuna-danilo-nunes.jpg",
	"C:/Hakuna-danilo-pacheco.jpg",
	"C:/Hakuna-danilo-ribeiro.jpg",
	"C:/Hakuna-davi-oliveira.jpg",
	"C:/Hakuna-davi-silva.jpg",
	"C:/Inari-abner-mateus.jpg",
	"C:/Inari-adnilton-santos.jpg",
	"C:/Inari-alan-luigi.jpg",
	"C:/Inari-alcymar-marcolino.jpg",
	"C:/Inari-alexandre-brina.jpg",
	"C:/Inari-alice-albuquerque.jpg",
	"C:/Inari-alvaro-caetano.jpg",
	"C:/Inari-amanda-dusse.jpg",
	"C:/Inari-amanda-moura.jpg",
	"C:/Inari-ana-santos.jpg",
	"C:/Inari-anaclara-souza.jpg",
	"C:/Inari-anaflavia-dias.jpg",
	"C:/Inari-anderson-sampaio.jpg",
	"C:/Inari-andre-filho.jpg",
	"C:/Inari-andre-guimaraes.jpg",
	"C:/Inari-andre-moraes.jpg",
	"C:/Inari-andressa-ederer.jpg",
	"C:/Inari-anna-lima.jpg",
	"C:/Inari-anna-lopes.jpg",
	"C:/Inari-antonio-rocha.jpg",
	"C:/Inari-arthur-castro.jpg",
	"C:/Inari-arthur-costa.jpg",
	"C:/Inari-arthur-hauck.jpg",
	"C:/Inari-arthur-miranda.jpg",
	"C:/Inari-augusto-scardua.jpg",
	"C:/Inari-barbara-mattioly.jpg",
	"C:/Inari-barbara-sampaio.jpg",
	"C:/Inari-barbara-soraggi.jpg",
	"C:/Inari-bianca-faria.jpg",
	"C:/Inari-brayan-silva.jpg",
	"C:/Inari-brenda-orlandi.jpg",
	"C:/Inari-breno-tana.jpg",
	"C:/Inari-bruna-rabelo.jpg",
	"C:/Inari-bruno-ramos.jpg",
	"C:/Inari-caio-gottmann.jpg",
	"C:/Inari-caique-francisco.jpg",
	"C:/Inari-camila-rodrigues.jpg",
	"C:/Inari-camila-silveira.jpg",
	"C:/Inari-camilla-teodoro.jpg",
	"C:/Inari-carolina-lobato.jpg",
	"C:/Inari-caroline-graciano.jpg",
	"C:/Inari-caroline-pires.jpg",
	"C:/Inari-christian-santos.jpg",
	"C:/Inari-cleiver-coelho.jpg",
	"C:/Inari-cristianne-rozendo.jpg",
	"C:/Inari-daiana-oliveira.jpg",
	"C:/Inari-danilo-paris.jpg",
	"C:/Inari-darlan-souza.jpg",
	"C:/Inari-davi-damartes.jpg",
	"C:/Inari-david-peixoto.jpg",
	"C:/Inari-deborah-matos.jpg",
	"C:/Inari-denilson-castro.jpg",
	"C:/Inari-denis-pereira.jpg",
	"C:/Inari-diego-froes.jpg",
	"C:/Inari-diego-ribeiro.jpg",
	"C:/Inari-diogo-graciano.jpg",
	"C:/Inari-diulia-almada.jpg",
	"C:/Novato-ana-gabriela.jpg",
	"C:/Novato-anna-gomes.jpg",
	"C:/Novato-beatriz-araujo.jpg",
	"C:/Novato-caixa-jbl.jpg",
	"C:/Novato-christian-vladimir.jpg",
	"C:/Rackers-abraao-vicentini.jpg",
	"C:/Rackers-adrianus-vieira.jpg",
	"C:/Rackers-alan-villela.jpg",
	"C:/Rackers-alberto-paschoal.jpg",
	"C:/Rackers-alessandro-pereira.jpg",
	"C:/Rackers-amanda-leal.jpg",
	"C:/Rackers-amanda-oliveira.jpg",
	"C:/Rackers-amanda-pires.jpg",
	"C:/Rackers-ana-candido.jpg",
	"C:/Rackers-ana-marcelino.jpg",
	"C:/Rackers-anacarolina-santos.jpg",
	"C:/Rackers-analuiza-caldas.jpg",
	"C:/Rackers-andre-palhares.jpg",
	"C:/Rackers-andreguilherme-macedo.jpg",
	"C:/Rackers-arthur-lima.jpg",
	"C:/Rackers-arthur-luiz.jpg",
	"C:/Rackers-arthur-muller.jpg",
	"C:/Rackers-augusto-baldiotti.jpg",
	"C:/Rackers-awa-maia.jpg",
	"C:/Rackers-barbara-rodrigues.jpg",
	"C:/Rackers-bernardo-davila.jpg",
	"C:/Rackers-betania-alves.jpg",
	"C:/Rackers-blenner-enes.jpg",
	"C:/Rackers-brener-rodrigues.jpg",
	"C:/Rackers-breno-moliveira.jpg",
	"C:/Rackers-breno-morais.jpg",
	"C:/Rackers-bruna-campos.jpg",
	"C:/Rackers-bruna-rolim.jpg",
	"C:/Rackers-bruno-bazzoni.jpg",
	"C:/Rackers-bruno-cesar.jpg",
	"C:/Rackers-caio-duarte.jpg",
	"C:/Rackers-caio-martinez.jpg",
	"C:/Rackers-caio-simoes.jpg",
	"C:/Rackers-camila-freitas.jpg",
	"C:/Rackers-camila-palhares.jpg",
	"C:/Rackers-carol-rodrigues.jpg",
	"C:/Rackers-carolina-reis.jpg",
	"C:/Rackers-caroline-rodrigues.jpg",
	"C:/Rackers-cinty-oliveira.jpg",
	"C:/Rackers-clara-mariano.jpg",
	"C:/Rackers-daniel-nogueira.jpg",
	"C:/Rackers-daniel-nunessilva.jpg",
	"C:/Rackers-danillo-lopes.jpg",
	"C:/Rackers-davidson-faria.jpg",
	"C:/Rackers-dhieinifer-andressa.jpg",
	"C:/Rubix-adriano-schettini.jpg",
	"C:/Rubix-alberto-junior.jpg",
	"C:/Rubix-alexandre-maia.jpg",
	"C:/Rubix-aline-lima.jpg",
	"C:/Rubix-alvaro-gontijo.jpg",
	"C:/Rubix-ana-decarvalho.jpg",
	"C:/Rubix-ana-diniz.jpg",
	"C:/Rubix-ana-guimaraes.jpg",
	"C:/Rubix-ana-velasque.jpg",
	"C:/Rubix-anaraphaela-oliveira.jpg",
	"C:/Rubix-andre-alves.jpg",
	"C:/Rubix-andre-jales.jpg",
	"C:/Rubix-andre-rocha.jpg",
	"C:/Rubix-angela-duarte.jpg",
	"C:/Rubix-angelo-assis.jpg",
	"C:/Rubix-aquila-souza.jpg",
	"C:/Rubix-arcanjo-ribeiro.jpg",
	"C:/Rubix-arlan-trindade.jpg",
	"C:/Rubix-arthur-bracarense.jpg",
	"C:/Rubix-arthur-lopes.jpg",
	"C:/Rubix-arthur-nunes.jpg",
	"C:/Rubix-barbara-araujo.jpg",
	"C:/Rubix-barbara-candido.jpg",
	"C:/Rubix-barbara-silverio.jpg",
	"C:/Rubix-beatriz-ferreira.jpg",
	"C:/Rubix-beatriz-zanon.jpg",
	"C:/Rubix-bernardo-andrade.jpg",
	"C:/Rubix-bernardo-costa.jpg",
	"C:/Rubix-braulio-almeida.jpg",
	"C:/Rubix-bremer-rodrigues.jpg",
	"C:/Rubix-caio-levy.jpg",
	"C:/Rubix-camila-ferreira.jpg",
	"C:/Rubix-camila-peres.jpg",
	"C:/Rubix-carla-victal.jpg",
	"C:/Rubix-cecilia-anjos.jpg",
	"C:/Rubix-cecilia-coelho.jpg",
	"C:/Rubix-cezar-ferreira.jpg",
	"C:/Rubix-cibele-silva.jpg",
	"C:/Rubix-clarice-palles.jpg",
	"C:/Rubix-daiane-camargo.jpg",
	"C:/Rubix-daniel-franca.jpg",
	"C:/Rubix-daniel-franco.jpg",
	"C:/Rubix-daniel-moreira.jpg",
	"C:/Rubix-daniel-silveira.jpg",
	"C:/Rubix-daniel-sousa.jpg",
	"C:/Rubix-danilo-alves.jpg",
	"C:/Rubix-debora-lacerda.jpg",
	"C:/Rubix-devidy-oliveira.jpg",
	"C:/Rubix-diego-sabadini.jpg",
	"C:/Rubix-douglas-cunha.jpg"
];
	 
































